[package]
name = "src-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
defmt = "0.3.8"
defmt-rtt = "0.4.1"
embedded-hal = "1.0.0"
panic-probe = { version = "0.3.2", features = ["print-defmt"] }
rp-pico = "0.9.0"
